resolving issue #43 and create separate file for the field names
wikitongues/Language-Indexing pull request #44
Opened 2021-07-28 08:39 UTC by d28601581

2021-07-28 08:46 UTC, d28601581 commented
The id_column for the airtable_items_table inside the user config file also needs to be changed from Url to Identifier to resolve the duplicated items issues.

[airtable_items_table]
table_name : External Resources
id_column : Url -> Identifier
page_size : 100

After I change that, there's no more duplicate items in the airtable but the items.jl will only have the new items added and not every single items. Not sure if that's what we want.

2021-07-29 00:05 UTC, smrohrer requested changes

2021-07-29 00:05 UTC, smrohrer commented on wikitongues/wikitongues/data_store/airtable/airtable_item_extractor.py
> +#    URL_FIELD, ISO_FIELD, LANGUAGE_FIELD, SPIDER_FIELD
Uncomment and use the imported field names

2021-07-29 22:37 UTC, smrohrer approved these changes

2021-07-29 22:37 UTC, merged